# Generated by Django 5.1.2 on 2024-10-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_users', '0002_alter_profile_birth'),
        ('tasks', '0002_rename_create_at_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='perfil_users.profile'),
        ),
    ]
