# Generated by Django 5.1.2 on 2024-10-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_timeentry_options_alter_task_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task'),
        ),
    ]
