# Generated by Django 5.1.2 on 2024-10-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_timeentry_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task'),
        ),
    ]
