# Generated by Django 5.1.2 on 2024-10-17 21:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_timeentry_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data da criaçao da tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='descrição da tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da tarefa'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(verbose_name='Data de inicio da tarefa'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='descrição do que foi feito na tarefa'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='estimated_time',
            field=models.CharField(max_length=20, verbose_name='estimativa do tempo'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task', verbose_name='Tarefa realcionada'),
        ),
    ]
