# Generated by Django 5.1.2 on 2024-10-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_created_at_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('feito', 'Feito'), ('reavaliar', 'Reavaliar')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
